theme: jekyll-theme-cayman

# Site settings
title: 曹振宇的个人博客				  	#你博客的标题
SEOTitle: 你的博客 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
email: zycarlton09@hotmail.com
description: "曹振宇的个人博客"  			 #网站介绍
keyword: "曹振宇，曹振宇的个人博客" #关键词
url: "https://carltoncao.github.io/"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写


# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "说点装逼的话。。。"
